%----------------------------------------------------------------------------------------------------
% "What we observe is not nature itself, but nature exposed to our method of questioning."
%                                                        — Werner Heisenberg
%----------------------------------------------------------------------------------------------------
% *[Overview]
%  This script illustrates the high frequency-resolution capability of SRSA using two real-valued
%  multitone signals composed of five and nine closely spaced sinusoidal components, respectively.
%  Because each real-valued sinusoid corresponds to a conjugate pair of complex exponentials, the
%  ground-truth model orders are K1_true = 10 for y1 and K2_true = 18 for y2.
%
%  In practical applications, however, the true model order is generally unknown. The present
%  experiment therefore uses the rule-based estimate K1_input = K2_input = 180, identified from
%  the elbow region of the corresponding singular-value spectra. The comparison between the known
%  model orders and the adopted rule-based values also illustrates the ability of SRSA to retain
%  closely spaced spectral components when K_input is conservatively overestimated.
%
% *[Caption for Figure (1)]
%      Panel (a): Simulated multitone signal y1.
%      Panel (b): Singular-value spectrum of the Hankel matrix constructed from y1, showing the
%                 ground-truth model order K1_true = 10 and the rule-based value K1_input = 180.
%      Panel (c): Full 2-D SRSA coherence response of y1 computed with K1_input = 180.
%      Panel (d): Bilateral Fourier amplitude spectrum of y1.
%      Panel (e): Full 2-D SRSA coherence response of y2 computed with K2_input = 180.
%      Panel (f): Bilateral Fourier amplitude spectrum of y2.
%      Panel (g): Simulated multitone signal y2.
%      Panel (h): Singular-value spectrum of the Hankel matrix constructed from y2, showing the
%                 ground-truth model order K2_true = 18 and the rule-based value K2_input = 180.
%      Panel (i): Selected Q_L range of the 2-D SRSA coherence response shown in panel (c).
%      Panel (j): Logarithmic stacked 1-D SRSA spectrum of y1.
%      Panel (k): Selected Q_L range of the 2-D SRSA coherence response shown in panel (e).
%      Panel (l): Logarithmic stacked 1-D SRSA spectrum of y2.
%
% *[Computational Environment]
%  The calculations were performed using MATLAB R2024b Update 3 on a workstation equipped with an
%  Intel Core i9-14900K processor (24 cores and 32 threads), 128 GB of RAM, and an NVIDIA GeForce
%  RTX 4090 D GPU with 24 GB of memory. The process-based parallel pool used eight workers. The
%  present implementation does not invoke GPU computing; therefore, the GPU did not contribute to
%  the reported runtimes.
%
% *[Representative Runtime]
%  The expected wall-clock time for this full-SVD demo is approximately 25 min on the stated
%  workstation. The runtime is dominated by the repeated complete SVDs of the Hankel matrices and
%  may vary with the parallel configuration and available memory.
%----------------------------------------------------------------------------------------------------
% Author       :   Zhifeng Chen
% E-mail       :   zfchen@whu.edu.cn
% Created      :   2026-01-20
% Last updated :   2026-06-20
%====================================================================================================

%% Data simulation

clc;
clear;

DeltaT = 1/365.25;                     % Sampling interval (yr)
t      = 1982.5:DeltaT:2023.5;         % Time (yr)
N      = numel(t);                     % Total number of samples

%  Amplitude  Frequency (cpy)
y1 = 1*cos(2*pi*1.180*t + 1.1) + ...
     1*cos(2*pi*1.185*t + 0.0) + ...
     1*cos(2*pi*1.190*t + 0.0) + ...
     1*cos(2*pi*1.195*t + 0.1) + ...
     1*cos(2*pi*1.200*t + 1.1);

y2 = 1*cos(2*pi*2.712*t) + ...
     1*cos(2*pi*2.723*t) + ...
     1*cos(2*pi*2.734*t) + ...
     1*cos(2*pi*2.745*t) + ...
     1*cos(2*pi*2.756*t) + ...
     1*cos(2*pi*2.767*t) + ...
     1*cos(2*pi*2.778*t) + ...
     1*cos(2*pi*2.789*t) + ...
     1*cos(2*pi*2.800*t);

%% Singular-value spectra

P = fix(N/2);                           % Number of Hankel columns
Q = N-P+1;                              % Number of Hankel rows

% Construct and decompose the Hankel matrix of y1.
H1 = zeros(Q,P);

for ii = 0:Q-1
    H1(ii+1,:) = y1(ii+1:ii+P);
end

singularV1  = svd(H1,'econ');           % Complete set of singular values
singularSN1 = (1:numel(singularV1)).';

clear H1

% Construct and decompose the Hankel matrix of y2.
H2 = zeros(Q,P);

for ii = 0:Q-1
    H2(ii+1,:) = y2(ii+1:ii+P);
end

singularV2  = svd(H2,'econ');           % Complete set of singular values
singularSN2 = (1:numel(singularV2)).';

clear H2

%% Fourier amplitude spectra

R1    = 200;                             
R2    = 200; 
Nfft = R1*N;
win  = hann(N);                         % Spectral window

% Bilateral frequency vector
FFTf = (-Nfft/2:Nfft/2-1).'/(Nfft*DeltaT);

% Bilateral spectra with exact window coherent-gain correction
FFTp1 = 2*abs(fftshift(fft(y1(:).*win,Nfft)))/sum(win);
FFTp2 = 2*abs(fftshift(fft(y2(:).*win,Nfft)))/sum(win);

%% SRSA spectra

tic;

Deltaf1 = 1/(DeltaT*N*R1);
Deltaf2 = 1/(DeltaT*N*R2);

bins1 = 1.17:Deltaf1:1.215;
bins2 = 2.60:Deltaf2:3.000;

% Ground-truth alternatives: K1_input = 10 and K2_input = 18.
% The present experiment uses the practical rule-based value K_input = 180.
K1_input = 180;
K2_input = 180;

[Bins1,LVEC1,SRSp1] = DoSRSA(y1,DeltaT,bins1,K1_input,'AlgorithmMode','svd');

[Bins2,LVEC2,SRSp2] = DoSRSA(y2,DeltaT,bins2,K2_input,'AlgorithmMode','svd');

toc;

%% Figure (1)

% Subwindow ranges used in the figure
displayQL = [8000,10000];
stackRows = 28:34;

stackQL1 = LVEC1(stackRows([1,end]),2);
stackQL2 = LVEC2(stackRows([1,end]),2);

fig1 = figure(1);
clf(fig1);

tiledlayout(4,8);
colormap('pink');

% Subplot (a): simulated sequence y1

nexttile(1,[2,2]);

plot(t,y1,'k-');

xlabel('Time (yr)','FontName','Times New Roman','FontSize',14);

ylabel('Amplitude','FontName','Times New Roman','FontSize',14);

legend('Simulated Sequence 1 ($y_1$)', ...
    'Box','off', ...
    'Interpreter','latex', ...
    'FontName','Times New Roman', ...
    'FontSize',16);

text(0.04,0.92,'(a)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

% Subplot (b): singular-value spectrum of y1

nexttile(3,[2,2]);

ld11 = plot(singularSN1,singularV1,'d-');
hold on;

xlim([-500,4500]);
ylim([-2/5,16/5]*1e-9);

xlabel('Singular-Value Index','FontName','Times New Roman','FontSize',14);

ylabel('Singular Value','FontName','Times New Roman','FontSize',14);

text(0.04,0.92,'(b)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

text(0.50,0.62,'Ground-truth-based $K_{input}=10$', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Interpreter','latex');

text(0.50,0.52,'Rule-based $K_{input}=180$', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Interpreter','latex');

yl    = [-2/5,16/5]*1e-9;
xBand = [130,230];

patch( ...
    [xBand(1),xBand(2),xBand(2),xBand(1)], ...
    [yl(1),yl(1),yl(2),yl(2)], ...
    [1,0,0], ...
    'FaceAlpha',0.15, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');

idx = singularSN1 == 180;

ld12 = plot(singularSN1(idx),singularV1(idx),'d', ...
    'MarkerEdgeColor','r', ...
    'MarkerFaceColor','r', ...
    'MarkerSize',4, ...
    'LineWidth',1.2);

hold off;

legend([ld11,ld12], ...
    'Singular-Value Spectrum','Spectrum Elbow', ...
    'Box','off', ...
    'FontName','Times New Roman', ...
    'FontSize',16);

set(gca,'Layer','top');

% Subplot (c): full 2D SRSA spectrum of y1

nexttile(5,[2,1]);

pcolor(Bins1,LVEC1(:,2),log(SRSp1));
shading interp;
hold on;

rectangle('Position',[1.17,displayQL(1),1.21-1.17,displayQL(2)-displayQL(1)], ...
          'EdgeColor','c', ...
          'LineWidth',1.5, ...
          'LineStyle','-');

hold off;

colorbar('northoutside','Color','k');

xlim([1.17,1.21]);

xlabel('Frequency (cpy)','FontName','Times New Roman','FontSize',14);

ylabel('$Q_L$','Interpreter','latex','FontName','Times New Roman','FontSize',14);

text(0.04,0.92,'(c)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Color','w');

text(0.10,0.87,'$y_1$ Coherence Response', ...
    'Units','normalized', ...
    'Color','m', ...
    'Interpreter','latex', ...
    'FontSize',14);

text(0.28,0.80,sprintf('($K_{input}=%d$)',K1_input), ...
    'Units','normalized', ...
    'Color','m', ...
    'Interpreter','latex', ...
    'FontSize',14);

text(0.02,0.56,'Selected trade-off range', ...
    'Units','normalized', ...
    'Color','c', ...
    'FontName','Times New Roman', ...
    'FontSize',10);

% Subplot (d): Fourier spectrum of y1

nexttile(6,[2,1]);

plot(FFTf,FFTp1,'k-');

xlim([1.06,1.31]);
ylim([0,5]);

ylabel('Amplitude','FontName','Times New Roman','FontSize',14);

text(0.20,0.90,'$y_1$ Fourier Spectrum', ...
    'Units','normalized', ...
    'Color','k', ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'Interpreter','latex');

text(0.06,0.90,'(d)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

% Subplot (e): full 2D SRSA spectrum of y2

nexttile(7,[2,1]);

pcolor(Bins2,LVEC2(:,2),log(SRSp2));
shading interp;
hold on;

rectangle('Position',[2.66,displayQL(1),2.85-2.66,displayQL(2)-displayQL(1)], ...
          'EdgeColor','c', ...
          'LineWidth',1.5, ...
          'LineStyle','-');

hold off;

colorbar('northoutside','Color','k');

xlim([2.66,2.85]);

xlabel('Frequency (cpy)','FontName','Times New Roman','FontSize',14);

ylabel('$Q_L$','Interpreter','latex','FontName','Times New Roman','FontSize',14);

text(0.04,0.92,'(e)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Color','w');

text(0.10,0.87,'$y_2$ Coherence Response', ...
    'Units','normalized', ...
    'Color','m', ...
    'Interpreter','latex', ...
    'FontSize',14);

text(0.28,0.80,sprintf('($K_{input}=%d$)',K2_input), ...
    'Units','normalized', ...
    'Color','m', ...
    'Interpreter','latex', ...
    'FontSize',14);

text(0.02,0.56,'Selected trade-off range', ...
    'Units','normalized', ...
    'Color','c', ...
    'FontName','Times New Roman', ...
    'FontSize',10);

% Subplot (f): Fourier spectrum of y2

nexttile(8,[2,1]);

plot(FFTf,FFTp2,'k-');

xlim([2.5,3.0]);
ylim([0,5]);

xlabel('Frequency (cpy)','FontName','Times New Roman','FontSize',14);

ylabel('Amplitude','FontName','Times New Roman','FontSize',14);

text(0.20,0.90,'$y_2$ Fourier Spectrum', ...
    'Units','normalized', ...
    'Color','k', ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'Interpreter','latex');

text(0.06,0.90,'(f)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

% Subplot (g): simulated sequence y2

nexttile(17,[2,2]);

plot(t,y2,'k-');

xlabel('Time (yr)','FontName','Times New Roman','FontSize',14);

ylabel('Amplitude','FontName','Times New Roman','FontSize',14);

legend('Simulated Sequence 2 ($y_2$)', ...
    'Box','off', ...
    'Interpreter','latex', ...
    'FontName','Times New Roman', ...
    'FontSize',16);

text(0.04,0.92,'(g)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

% Subplot (h): singular-value spectrum of y2

nexttile(19,[2,2]);

ld21 = plot(singularSN2,singularV2,'d-');
hold on;

xlim([-500,4500]);
ylim([-1/5,9/5]*1e-8);

xlabel('Singular-Value Index','FontName','Times New Roman','FontSize',14);

ylabel('Singular Value','FontName','Times New Roman','FontSize',14);

text(0.04,0.92,'(h)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

text(0.50,0.62,'Ground-truth-based $K_{input}=18$', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Interpreter','latex');

text(0.50,0.52,'Rule-based $K_{input}=180$', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Interpreter','latex');

yl    = [-1/5,9/5]*1e-8;
xBand = [130,230];

patch( ...
    [xBand(1),xBand(2),xBand(2),xBand(1)], ...
    [yl(1),yl(1),yl(2),yl(2)], ...
    [1,0,0], ...
    'FaceAlpha',0.15, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');

idx = singularSN2 == 180;

ld22 = plot(singularSN2(idx),singularV2(idx),'d', ...
    'MarkerEdgeColor','r', ...
    'MarkerFaceColor','r', ...
    'MarkerSize',4, ...
    'LineWidth',1.2);

hold off;

legend([ld21,ld22], ...
    'Singular-Value Spectrum','Spectrum Elbow', ...
    'Box','off', ...
    'FontName','Times New Roman', ...
    'FontSize',16);

set(gca,'Layer','top');

% Subplot (i): selected trade-off range of y1

nexttile(21,[2,1]);

pcolor(Bins1,LVEC1(:,2),log(SRSp1));
shading interp;

colorbar('northoutside','Color','k');

xlim([1.17,1.21]);
ylim(displayQL);

ylabel('$Q_L$', ...
    'Interpreter','latex', ...
    'FontName','Times New Roman', ...
    'FontSize',14);

text(0.06,0.90,'(i)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Color','w');

text(0.17,0.90,'$y_1$ Coherence Response', ...
    'Units','normalized', ...
    'Color','m', ...
    'Interpreter','latex', ...
    'FontSize',14);

text(0.10,0.10, ...
    sprintf('$Q_L \\in [%d,%d]$', ...
    displayQL(1),displayQL(2)), ...
    'Units','normalized', ...
    'Color','c', ...
    'Interpreter','latex', ...
    'FontWeight','bold');

% Subplot (j): stacked 1D SRSA spectrum of y1

nexttile(22,[2,1]);

stackedSRSp1 = mean(SRSp1(stackRows,:),1);
plot(Bins1,log(stackedSRSp1),'k-');

xlim([1.17,1.21]);
ylim([-30,5]);

xlabel('Frequency (cpy)','FontName','Times New Roman','FontSize',14);

ylabel('Logarithmic Coherence Response','FontName','Times New Roman','FontSize',14);

text(0.15,0.90,'$y_1$ 1D SRSA Spectrum', ...
    'Units','normalized', ...
    'Color','k', ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'Interpreter','latex');

text(0.06,0.90,'(j)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

text(0.15,0.10, ...
    sprintf('Stacking $Q_L \\in [%d,%d]$', ...
    stackQL1(1),stackQL1(2)), ...
    'Units','normalized', ...
    'Color','k', ...
    'Interpreter','latex', ...
    'FontWeight','bold');

% Subplot (k): selected trade-off range of y2

nexttile(23,[2,1]);

pcolor(Bins2,LVEC2(:,2),log(SRSp2));
shading interp;

colorbar('northoutside','Color','k');

xlim([2.70,2.81]);
ylim(displayQL);

xlabel('Frequency (cpy)','FontName','Times New Roman','FontSize',14);

ylabel('$Q_L$', ...
    'Interpreter','latex', ...
    'FontName','Times New Roman', ...
    'FontSize',14);

text(0.06,0.90,'(k)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'Color','w');

text(0.17,0.90,'$y_2$ Coherence Response', ...
    'Units','normalized', ...
    'Color','m', ...
    'Interpreter','latex', ...
    'FontSize',14);

text(0.10,0.10, ...
    sprintf('$Q_L \\in [%d,%d]$', ...
    displayQL(1),displayQL(2)), ...
    'Units','normalized', ...
    'Color','c', ...
    'Interpreter','latex', ...
    'FontWeight','bold');

% Subplot (l): stacked 1D SRSA spectrum of y2

nexttile(24,[2,1]);

stackedSRSp2 = mean(SRSp2(stackRows,:),1);
plot(Bins2,log(stackedSRSp2),'k-');

xlim([2.70,2.81]);
ylim([-22,5]);

xlabel('Frequency (cpy)','FontName','Times New Roman','FontSize',14);

ylabel('Logarithmic Coherence Response','FontName','Times New Roman','FontSize',14);

text(0.15,0.90,'$y_2$ 1D SRSA Spectrum', ...
    'Units','normalized', ...
    'Color','k', ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'Interpreter','latex');

text(0.06,0.90,'(l)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',12);

text(0.15,0.10, ...
    sprintf('Stacking $Q_L \\in [%d,%d]$', ...
    stackQL2(1),stackQL2(2)), ...
    'Units','normalized', ...
    'Color','k', ...
    'Interpreter','latex', ...
    'FontWeight','bold');